[package]
name = "rusty-gpib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.9.1"
bytes = "1.10"
thiserror = "2.0"

[build-dependencies]
bindgen = "0.72"
